server:
  port: 8888


#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  #实体类所做包
  type-aliases-package: com.echarts.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  config: src\main\resources\log4j.properties

---

#开发配置
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #设置查询连接语句
    validationQuery: SELECT 1 FROM DUAL

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    logSlowSql: true